<?php


/**
 * Implements hook_schema().
 */
function myassist_achievements_schema() {
  $schema['myassist_achievements_levels'] = array(
    'description' => t('Gamification levels'),
    'fields' => array(
      'level' => array(
        'description' => 'Level number',
        'type' => 'int',
        'unsigned' => true,
        'not null' => true,
      ),
      'points' => array(
        'description' => 'Points required',
        'type' => 'int',
        'unsigned' => true,
        'not null' => true,
      ),
      'title' => array(
        'description' => 'User title key at level',
        'type' => 'varchar',
        'length' => 25,
      ),
    ),
    'primary key' => array('level')
  );
  $schema['myassist_pending_point_display'] = array(
    'description' => t('Gained point transactions yet to be displayed'),
    'fields' => array(
      'uid' => array(
        'description' => 'User id',
        'type' => 'int',
        'unsigned' => true,
        'not null' => true,
      ),
      'txid' => array(
        'description' => 'Transaction id',
        'type' => 'int',
        'unsigned' => true,
        'not null' => true,
      ),
    )
    );
  return $schema;
}



function myassist_achievements_install() {
    $k = 10;
    $factor = 1.1;
    $q = db_insert('myassist_achievements_levels')->fields(array('level','points','title'));
    for ($level=0; $level<=100; $level++) {
        $points = $level > 0 ? ceil( ($k / ($factor - 1)) * (pow($factor, $level) - 1) ) : 0;
        $key = "Level " . $level;
        $q->values(array(
          (int) $level,
          (int) $points,
          $key
        ));
        t($key);
    }
    $q->execute();
}
