<?php


/**
 * Implements hook_schema().
 */
function myassist_achievements_schema() {
  $schema['myassist_achievements_levels'] = array(
    'description' => t('Gamification levels'),
    'fields' => array(
      'level' => array(
        'description' => 'Level number',
        'type' => 'int',
        'unsigned' => true,
        'not null' => true,
      ),
      'points' => array(
        'description' => 'Points required',
        'type' => 'int',
        'unsigned' => true,
        'not null' => true,
      ),
      'title' => array(
        'description' => 'User title key at level',
        'type' => 'varchar',
        'length' => 25,
      ),
    ),
    'primary key' => array('level')
  );
  $schema['myassist_pending_point_display'] = array(
    'description' => t('Gained point transactions yet to be displayed'),
    'fields' => array(
      'uid' => array(
        'description' => 'User id',
        'type' => 'int',
        'unsigned' => true,
        'not null' => true,
      ),
      'txid' => array(
        'description' => 'Transaction id',
        'type' => 'int',
        'unsigned' => true,
        'not null' => true,
      ),
    )
    );
  return $schema;
}



function myassist_achievements_install() {
  $q = db_insert('myassist_achievements_levels')->fields(array('level','points','title'));
  $q->values(array(0, 0, t("Level 0")));
  $q->values(array(1, 100, t("Level 1")));
  $q->values(array(2, 200, t("Level 2")));
  $q->values(array(3, 400, t("Level 3")));
  $q->values(array(4, 700, t("Level 4")));
  $q->values(array(5, 1200, t("Level 5")));
  $q->values(array(6, 2000, t("Level 6")));
  $q->values(array(7, 3500, t("Level 7")));
  $q->values(array(8, 6000, t("Level 8")));
  $q->values(array(9, 10000, t("Level 9")));
  $q->values(array(10, 15000, t("Level 10")));
  $q->execute();
}
