<?php
/**
 * @file
 * Code for the MyAssist Opeka chat integration.
 */

function is_opeka_chat_page() {
    return array_key_exists(current_path(), array(
        'opeka' => TRUE,
        'admin/opeka' => TRUE
    ));
}


/**
 * Implements hook_page_build().
 */
function myassist_opeka_page_build(&$page)
{
    global $user;
    $module_path = drupal_get_path('module', 'myassist_opeka');

    $template_path = dirname(__FILE__) . '/templates/';

    $is_chat_page = is_opeka_chat_page();
    if($is_chat_page) {
        drupal_add_js($module_path . '/js/chat-page-integration.js', array('weight' => 10));
        drupal_add_css($module_path . '/css/myassist_opeka.css');
        # Add page content
        $page['content']['myassist-opeka-templates'] = array(
            '#markup' => file_get_contents($template_path . 'chat-pages.tmpl.html')
        );
        $settings = array();
        if($user->uid) {
            // Opeka needs this to validate the user. Might be removed if the user opts to be anonymous
            // in the signIn form
            $settings['user'] = array (
                'uid' => (integer) $user->uid,
                'sid' => $user->sid
            );

            $settings['logged_into_drupal'] = TRUE;
            $settings['drupal_user_uid'] = $user->uid;
            $settings['drupal_user_name'] = $user->name;

            $gender_fieldname = "field_gender_adult";
            $user_profile = profile2_load_by_user($user, 'voksenprofil');
            if(!$user_profile) {
                $gender_fieldname = "field_gender";
                $user_profile = profile2_load_by_user($user, 'ungeprofil');
            }

            if($user_profile) {
                $birthday = field_get_items("profile2", $user_profile, "field_birthday");
                if(is_array($birthday) && count($birthday) && array_key_exists('value', $birthday[0])) {
                    $diff = date_diff(DateTime::createFromFormat('U', $birthday[0]['value']), new DateTime());
                    $settings['drupal_user_age'] = $diff->y;
                }
                $gender_field = field_get_items("profile2", $user_profile, $gender_fieldname);

                // TODO: probably some way to get this from metadata?
                $gender_map = array(
                    "0" => "m",
                    "1" => "f"
                );

                if(is_array($gender_field) && count($gender_field) && array_key_exists('value', $gender_field[0])) {
                    $gender_value = $gender_field[0]['value'];
                    if(array_key_exists($gender_value, $gender_map)) {
                        $gender_value = $gender_map[$gender_value];
                    } else {
                        $gender_value = '';
                    }
                    $settings['drupal_user_gender'] = $gender_value;
                }
            }
        }

        drupal_add_js(array('opeka' => $settings), 'setting');
    } else {
        // Skip admin pages
        if(strpos(current_path(), "admin") !== false) {
            return;
        }
        /* TODO: socket.io client updates from the chat

        drupal_add_js('https://cdn.socket.io/socket.io-1.3.5.js');
        drupal_add_js($module_path . '/js/other-pages-integration.js', array('weight' => 10));

        # Add page content
        $page['content']['myassist-opeka-templates'] = array(
            '#markup' => file_get_contents($template_path . 'other-pages.tmpl.html')
        );
        */
    }

    return $page;
}

/**
 * Implements hook_theme_registry_alter().
 */
function myassist_opeka_theme_registry_alter(&$theme_registry)
{
    // Defined path to the current module.
    $module_path = drupal_get_path('module', 'myassist_opeka');

    // Find all .tpl.php files in this module's folder recursively.
    $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);

    // Iterate through all found template file objects.
    foreach ($template_file_objects as $key => $template_file_object) {
        // If the template has not already been overridden by a theme.
        if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
            // Alter the theme path and template elements.
            $theme_registry[$key]['theme path'] = $module_path;
            $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
            $theme_registry[$key]['type'] = 'module';
        }
    }
}

/**
 * Implements hook_page_alter().
 */
function myassist_opeka_page_alter(&$page)
{
    if(is_opeka_chat_page()) {
        // Override the page template
        $page['#theme'] = 'page__myassist_opeka';

        // Remove unwanted items
        $remove_items = array(
            'header',
            'page_top',
            'sidebar_first',
            'footer'
        );

        foreach($remove_items as $key) {
            if(array_key_exists($key, $page)) {
                unset($page[$key]);
            }
        }
    }
    return $page;
}
