<?php
/**
 * @file
 * Code for the MyAssist Opeka chat integration.
 */

/**
 * Implements hook_help().
function myassist_opeka_help($path, $arg)
{
    return '<p>' . t('Integration with Opeka chat module') . '</p>';
}
 */

/**
 * Implements hook_page_build().
 */
function myassist_opeka_page_build(&$page)
{
    global $user;
    $module_path = drupal_get_path('module', 'myassist_opeka');


    $template_path = dirname(__FILE__) . '/templates/';

    $is_chat_page = strpos(current_path(), "opeka") !== false;
    if($is_chat_page) {
        drupal_add_js($module_path . '/js/chat-page-integration.js', array('weight' => 10));
        drupal_add_css($module_path . '/css/myassist_opeka.css');
        # Add page content
        $page['content']['myassist-opeka-templates'] = array(
            '#markup' => file_get_contents($template_path . 'chat-pages.tmpl.html')
        );
        $settings = array();
        if($user->uid) {
            // Opeka needs this to validate the user. Might be removed if the user opts to be anonymous
            // in the signIn form
            $settings['user'] = array (
                'uid' => (integer) $user->uid,
                'sid' => $user->sid
            );

            $settings['logged_into_drupal'] = TRUE;
            $settings['drupal_user_uid'] = $user->uid;
            $settings['drupal_user_name'] = $user->name;

            $gender_fieldname = "field_gender_adult";
            $user_profile = profile2_load_by_user($user, 'voksenprofil');
            if(!$user_profile) {
                $gender_fieldname = "field_gender";
                $user_profile = profile2_load_by_user($user, 'ungeprofil');
            }

            $birthday = field_get_items("profile2", $user_profile, "field_birthday");
            if(is_array($birthday) && count($birthday) && array_key_exists('value', $birthday[0])) {
                $diff = date_diff(DateTime::createFromFormat('U', $birthday[0]['value']), new DateTime());
                $settings['drupal_user_age'] = $diff->y;
            }
            $gender_field = field_get_items("profile2", $user_profile, $gender_fieldname);

            // TODO: probably some way to get this from metadata?
            $gender_map = array(
                "0" => "m",
                "1" => "f"
            );

            if(is_array($gender_field) && count($gender_field) && array_key_exists('value', $gender_field[0])) {
                $gender_value = $gender_field[0]['value'];
                if(array_key_exists($gender_value, $gender_map)) {
                    $gender_value = $gender_map[$gender_value];
                } else {
                    $gender_value = '';
                }
                $settings['drupal_user_gender'] = $gender_value;
            }
            
        }

        drupal_add_js(array('opeka' => $settings), 'setting');
    } else {
        // Skip admin pages
        if(strpos(current_path(), "admin") !== false) {
            return;
        }
        /* TODO: socket.io client updates from the chat

        drupal_add_js('https://cdn.socket.io/socket.io-1.3.5.js');
        drupal_add_js($module_path . '/js/other-pages-integration.js', array('weight' => 10));

        # Add page content
        $page['content']['myassist-opeka-templates'] = array(
            '#markup' => file_get_contents($template_path . 'other-pages.tmpl.html')
        );
        */
    }
}

