<?php
/**
 * @file
 * Code for the MyAssist User feature.
 */

include_once 'myassist_user.features.inc';

/**
 * Implements hook_profile2_view().
 */
function myassist_user_profile2_view($profile, $view_mode, $langcode) {
  $uid = $profile->uid;

  $profile->content['userinfo'] = array(
    '#theme' => "myassist_userinfo",
    "#gender" => $profile->content["field_gender"],
    "#age" => $profile->content["field_age"]
  );
  unset($profile->content["field_gender"]);
  unset($profile->content["field_age"]);


  $profile->content['username'] = array(
    '#theme' => "myassist_username", // Point to definition in myassist_achievements_theme
    '#weight' => 0,
    '#title' => 'Username',
    '#name' => $profile->user()->name, // Pass data to template (name must be defined in the definition)
  );
  $profile->content['membersince'] = array(
    '#theme' => "myassist_membersince", // Point to definition in myassist_achievements_theme
    '#weight' => 0,
    '#title' => 'Membersince',
    '#created' => date('d.m.Y', $profile->created),
  );

  $profile->content['nodes'] = array(
    '#markup' => views_embed_view("user_nodes", 'default', $uid),
  );
}

/**
 * Implements hook_user_view().
 */
function myassist_user_user_view($account, $view_mode, $langcode) {
  unset($account->content['user_picture']); // Sabotage user picture; we'll display it ourselves
  unset($account->content['userpoints']); // Sabotage points display from function userpoints_user_view in the userpoints module
  unset($account->content['summary']); // Sabotage history display; we'll display it ourselves

}

/**
 * Implements hook_theme().
 */
function myassist_user_theme($existing, $type, $theme, $path){
  return array(
    'myassist_username' => array(
      'template' => 'templates/myassist_username', // define myassist_points.tpl.php inside module - point to myassist_achievements/templates/myassist_points.tpl.php
      'variables' => array('name' => NULL), //define all variables used in the template file
    ),
    'myassist_membersince' => array(
      'template' => 'templates/myassist_membersince', // define myassist_points.tpl.php inside module - point to myassist_achievements/templates/myassist_points.tpl.php
      'variables' => array('created' => NULL), //define all variables used in the template file
    ),
    'myassist_userinfo' => array(
      'template' => 'templates/myassist_userinfo', // define myassist_points.tpl.php inside module - point to myassist_achievements/templates/myassist_points.tpl.php
      'variables' => array('gender' => NULL, 'age' => NULL), //define all variables used in the template file
    ),
  );
}